# Generated by Django 3.2.6 on 2021-10-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0003_auto_20211018_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyercompany',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='ORGN'),
        ),
        migrations.AlterField(
            model_name='buyercompany',
            name='phone',
            field=models.TextField(blank=True, null=True, verbose_name='Phone'),
        ),
    ]
