# Generated by Django 3.2.6 on 2021-10-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0004_auto_20211018_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerperson',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
