# Generated by Django 3.2.6 on 2021-10-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0005_rename_full_name_buyerperson_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrmanager',
            name='sro_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
