# Generated by Django 3.2.6 on 2021-10-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0006_arbitrmanager_sro_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='examination_date',
            field=models.DateField(blank=True, null=True, verbose_name='ExaminationDate'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date_begin',
            field=models.DateField(blank=True, null=True, verbose_name='Meeting_date_begin'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='RegistrationDate'),
        ),
    ]
