# Generated by Django 3.2.6 on 2021-10-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0007_auto_20211018_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnullmentMessage',
            new_name='AnnullmentMessage',
        ),
    ]
