# Generated by Django 3.2.6 on 2021-10-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0008_rename_anullmentmessage_annullmentmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsessionstatistic',
            name='date_begin',
            field=models.DateField(blank=True, null=True, verbose_name='DateBegin'),
        ),
    ]
