# Generated by Django 3.2.6 on 2021-10-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0009_alter_applicationsessionstatistic_date_begin'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedata',
            name='id_message_data',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractinfo',
            name='date_contract',
            field=models.DateField(blank=True, null=True, verbose_name='DateContract'),
        ),
    ]
