# Generated by Django 3.2.6 on 2021-10-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0011_rename_publisher_publisher_xsi_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sro',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='sro',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='ORGN'),
        ),
    ]
