# Generated by Django 3.2.6 on 2021-10-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0012_auto_20211022_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sro',
            name='inn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='OGRN'),
        ),
    ]
