# Generated by Django 3.2.6 on 2021-10-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0013_auto_20211022_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetDebtorMessagesContentForPeriodByIdBankrupt',
        ),
        migrations.AddField(
            model_name='getmessagecontent',
            name='get_message_content_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентификатор сообщения в ЕФРСБ'),
        ),
        migrations.AlterField(
            model_name='arbitrmanager',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='arbitrmanager',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='arbitrmanager',
            name='sro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.sro'),
        ),
        migrations.AlterField(
            model_name='bankrupt_company_v2',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='bankrupt_company_v2',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.category'),
        ),
        migrations.AlterField(
            model_name='bankrupt_company_v2',
            name='inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='bankrupt_company_v2',
            name='name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bankrupt_company_v2',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='bankrupt_person_v2',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='bankrupt_person_v2',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.category'),
        ),
        migrations.AlterField(
            model_name='bankrupt_person_v2',
            name='fio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.fio'),
        ),
        migrations.AlterField(
            model_name='bankruptfirm',
            name='full_name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='FullName'),
        ),
        migrations.AlterField(
            model_name='bankruptfirm',
            name='insolvent_catrory_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='InsolventCategoryName'),
        ),
        migrations.AlterField(
            model_name='bankruptfirm',
            name='legal_addres',
            field=models.CharField(blank=True, max_length=300, verbose_name='LegalAddress'),
        ),
        migrations.AlterField(
            model_name='bankruptfirm',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='bankruptfirm',
            name='okpo',
            field=models.CharField(blank=True, max_length=8, verbose_name='OKPO'),
        ),
        migrations.AlterField(
            model_name='bankruptfirm',
            name='post_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='PostAddress'),
        ),
        migrations.AlterField(
            model_name='bankruptfirm',
            name='short_name',
            field=models.CharField(blank=True, max_length=512, verbose_name='ShortName'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='insolvent_catrory_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='InsolventCategoryName'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='ogrnip',
            field=models.CharField(blank=True, max_length=15, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='fio',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='fio',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='fiohistory',
            name='fio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.fio'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizer',
            name='full_name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='FullName'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizer',
            name='inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizer',
            name='legal_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='LegalAddress'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizer',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizer',
            name='okpo',
            field=models.CharField(blank=True, max_length=8, verbose_name='OKPO'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizer',
            name='post_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='PostAddress'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizer',
            name='short_name',
            field=models.CharField(blank=True, max_length=512, verbose_name='ShortName'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizeragent',
            name='firm_trade_organizer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.firmtradeorganizer', verbose_name='FirmTradeOrganizer'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizeragent',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizeragent',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizeragent',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='MiddleName'),
        ),
        migrations.AlterField(
            model_name='fnsdepartment',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='fnsdepartment',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='foreignsystem',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='getmessagecontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='message_guid',
            field=models.CharField(blank=True, max_length=32, verbose_name='MessageGUID'),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='publish_data',
            field=models.DateTimeField(blank=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='messageinfo',
            name='message_types',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.messagetypes'),
        ),
        migrations.AlterField(
            model_name='messageurl',
            name='download_size',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='messageurl',
            name='url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='messageurl',
            name='url_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='organization_department_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='OrganizationDepartmentName'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='organization_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='OrganizationName'),
        ),
        migrations.AlterField(
            model_name='operatorsro',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='operatorsro',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='operatorsro',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='MiddleName'),
        ),
        migrations.AlterField(
            model_name='operatorsro',
            name='sro_info',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.sroinfo', verbose_name='SroInfo'),
        ),
        migrations.AlterField(
            model_name='participantcompany',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='ORGN'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='person',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='persontradeorganizer',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='persontradeorganizer',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='persontradeorganizer',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='persontradeorganizer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='persontradeorganizer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='MiddleName'),
        ),
        migrations.AlterField(
            model_name='persontradeorganizer',
            name='ogrnip',
            field=models.CharField(blank=True, max_length=15, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='xsi_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_sro_v2',
            name='address',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_sro_v2',
            name='inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_sro_v2',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_sro_v2',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_v2',
            name='correspondence_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Correspondence Address'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_v2',
            name='fio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.fio'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_v2',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_v2',
            name='snils',
            field=models.CharField(blank=True, max_length=11, verbose_name='SNILS'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_v2',
            name='sro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.sro'),
        ),
        migrations.AlterField(
            model_name='publisher_asv_v2',
            name='inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_asv_v2',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_centralbankrf_v2',
            name='inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_centralbankrf_v2',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_company_v2',
            name='inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_company_v2',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_efrsb_v2',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_firmtrade_organizer_v2',
            name='inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_firmtrade_organizer_v2',
            name='name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_firmtrade_organizer_v2',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='publisher_fnsdepartment_v2',
            name='inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_fnsdepartment_v2',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_mfc_v2',
            name='inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_mfc_v2',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_person_v2',
            name='fio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.fio'),
        ),
        migrations.AlterField(
            model_name='publisher_person_v2',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_persontrade_organizer_v2',
            name='fio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.fio'),
        ),
        migrations.AlterField(
            model_name='publisher_persontrade_organizer_v2',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='sro_name',
            field=models.CharField(blank=True, max_length=512, verbose_name='SroName'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='sro_registry_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='SroRegistryNumber'),
        ),
        migrations.AlterField(
            model_name='sroinfo',
            name='inn',
            field=models.CharField(blank=True, max_length=15, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='sroinfo',
            name='legal_address',
            field=models.CharField(blank=True, max_length=1024, verbose_name='LegalAddress'),
        ),
        migrations.AlterField(
            model_name='sroinfo',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sroinfo',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='sroinfo',
            name='post_address',
            field=models.CharField(blank=True, max_length=1024, verbose_name='PostAddress'),
        ),
    ]
