# Generated by Django 3.2.6 on 2021-10-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0014_auto_20211022_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetDebtorMessagesContentForPeriodByIdBankrupt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bankrupt', models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор должника')),
                ('startDate', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала периода')),
            ],
        ),
    ]
