# Generated by Django 3.2.6 on 2021-10-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0015_getdebtormessagescontentforperiodbyidbankrupt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getdebtormessagescontentforperiodbyidbankrupt',
            old_name='Bankrupt',
            new_name='id_Bankrupt',
        ),
    ]
