# Generated by Django 3.2.6 on 2021-10-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0016_rename_bankrupt_getdebtormessagescontentforperiodbyidbankrupt_id_bankrupt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='publisher_arbitr_manager_sro_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.publisher_arbitr_manager_sro_v2'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_asv_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.publisher_asv_v2'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_centralbankrf_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.publisher_centralbankrf_v2'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_company_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.publisher_company_v2'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_efrsb_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.publisher_efrsb_v2'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_firmtrade_organizer_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.publisher_firmtrade_organizer_v2'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_fnsdepartment_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.publisher_fnsdepartment_v2'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_mfc_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.publisher_mfc_v2'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_person_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.publisher_person_v2'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_persontrade_organizer_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.publisher_persontrade_organizer_v2'),
        ),
    ]
