# Generated by Django 3.2.6 on 2021-10-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0017_auto_20211022_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='publisher_arbitr_manager_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.publisher_arbitr_manager_v2'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='xsi_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Publisher'),
        ),
    ]
