# Generated by Django 3.2.6 on 2021-10-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0018_auto_20211022_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagedata',
            name='publish_data',
        ),
        migrations.AddField(
            model_name='messagedata',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
