# Generated by Django 3.2.6 on 2021-10-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0019_auto_20211022_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='bankrupt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.bankrupt', verbose_name='Bankrupt'),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='bankrupt_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.bankruptinfo', verbose_name='BankruptInfo'),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='bankruptid',
            field=models.IntegerField(blank=True, null=True, verbose_name='BankruptId'),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='case_number',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Номер судебного дела'),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='file_info_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.fileinfolist', verbose_name='FileInfoList'),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='message_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.messageinfo', verbose_name='MessageInfo'),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='message_url_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.messageurllist', verbose_name='MessageURLList'),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер сообщения'),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.publisher', verbose_name='Publsher'),
        ),
    ]
