# Generated by Django 3.2.6 on 2021-10-22 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0020_auto_20211022_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='message_guid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='MessageGUID'),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='publisher_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.publisherinfo', verbose_name='PublisherInfo'),
        ),
    ]
