# Generated by Django 3.2.6 on 2021-10-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0021_auto_20211022_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtdecision',
            name='citizen_not_released_from_responsibility',
            field=models.TextField(blank=True, null=True, verbose_name='CitizenNotReleasedFromResponsibility'),
        ),
        migrations.AlterField(
            model_name='courtdecision',
            name='creditor_claim_register_close_date',
            field=models.TextField(blank=True, null=True, verbose_name='CreditorClaimRegisterCloseDate'),
        ),
        migrations.AlterField(
            model_name='courtdecision',
            name='creditor_claim_setting_requirement_expiration_date',
            field=models.TextField(blank=True, null=True, verbose_name='CreditorClaimSettingRequirementsExpirationDate'),
        ),
        migrations.AlterField(
            model_name='courtdecision',
            name='decision_made_due_tor_cancellation_restructuring_plan',
            field=models.TextField(blank=True, null=True, verbose_name='DecisionMadeDueTorCancellationRestructuringPlan'),
        ),
        migrations.AlterField(
            model_name='courtdecision',
            name='next_court_session_date',
            field=models.TextField(blank=True, null=True, verbose_name='NextCourtSessionDate'),
        ),
    ]
