# Generated by Django 3.2.6 on 2021-10-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0022_auto_20211025_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisiontype',
            name='Id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
