# Generated by Django 3.2.6 on 2021-10-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0023_decisiontype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrmanagerinfo',
            name='Id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
