# Generated by Django 3.2.6 on 2021-10-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0024_arbitrmanagerinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='examination_date',
            field=models.TextField(blank=True, null=True, verbose_name='ExaminationDate'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.TextField(blank=True, null=True, verbose_name='MeetingDate'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date_begin',
            field=models.TextField(blank=True, null=True, verbose_name='Meeting_date_begin'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_time_begin',
            field=models.TextField(blank=True, null=True, verbose_name='MeetingTimeBegin'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='registration_date',
            field=models.TextField(blank=True, null=True, verbose_name='RegistrationDate'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='registration_date_begin',
            field=models.TextField(blank=True, null=True, verbose_name='RegistrationDateBegin'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='registration_date_end',
            field=models.TextField(blank=True, null=True, verbose_name='RegistrationDateEnd'),
        ),
    ]
