# Generated by Django 3.2.6 on 2021-10-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0025_auto_20211025_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='examination_site',
            field=models.TextField(blank=True, null=True, verbose_name='ExaminatationSite'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='registration_site',
            field=models.TextField(blank=True, null=True, verbose_name='RegistrationSite'),
        ),
    ]
