# Generated by Django 3.2.6 on 2021-10-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0026_auto_20211025_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='fu_mail_address',
            field=models.TextField(blank=True, null=True, verbose_name='FuMailAddress'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_form',
            field=models.TextField(blank=True, null=True, verbose_name='MeetingForm'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='web_address',
            field=models.TextField(blank=True, null=True, verbose_name='WebAddress'),
        ),
    ]
