# Generated by Django 3.2.6 on 2021-10-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0027_auto_20211025_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantcompany',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='participantcompany',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
    ]
