# Generated by Django 3.2.6 on 2021-10-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0028_auto_20211025_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='id_arbitr_manager',
            field=models.TextField(blank=True, null=True, verbose_name='IdAritrManager'),
        ),
    ]
