# Generated by Django 3.2.6 on 2021-10-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0029_alter_director_id_arbitr_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecontractresult2',
            name='id_auction_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
