# Generated by Django 3.2.6 on 2021-10-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0030_alter_salecontractresult2_id_auction_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingworker',
            name='meeting_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
