# Generated by Django 3.2.6 on 2021-10-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0033_auto_20211026_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
