# Generated by Django 3.2.6 on 2021-10-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0034_message_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertdecision',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
