# Generated by Django 3.2.6 on 2021-10-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0035_alter_expertdecision_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OblegatoryPayment',
            new_name='ObligatoryPayment',
        ),
        migrations.RenameModel(
            old_name='OblegatoryPayments',
            new_name='ObligatoryPayments',
        ),
    ]
