# Generated by Django 3.2.6 on 2021-10-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0036_auto_20211027_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrupt',
            name='bankrupt_company_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.bankrupt_company_v2'),
        ),
        migrations.AlterField(
            model_name='bankrupt',
            name='bankrupt_person_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.bankrupt_person_v2'),
        ),
    ]
