# Generated by Django 3.2.6 on 2021-10-28 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0038_auto_20211028_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrupt_company_v2',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='bankrupt_company_v2',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.category'),
        ),
        migrations.AlterField(
            model_name='bankrupt_company_v2',
            name='inn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='bankrupt_company_v2',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bankrupt_company_v2',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
