# Generated by Django 3.2.6 on 2021-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0039_auto_20211028_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrupt_person_v2',
            name='birth_date',
            field=models.TextField(blank=True, null=True, verbose_name='BirthDate'),
        ),
    ]
