# Generated by Django 3.2.6 on 2021-10-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0041_alter_messageinfo_message_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetypes',
            old_name='liabilities_creditor_org',
            new_name='liabilities_credit_org',
        ),
    ]
