# Generated by Django 3.2.6 on 2021-10-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0042_rename_liabilities_creditor_org_messagetypes_liabilities_credit_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetypes',
            old_name='perfomance_creditor_org',
            new_name='perfomance_credit_org',
        ),
    ]
