# Generated by Django 3.2.6 on 2021-10-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0044_rename_cancel_autction_trade_result_messagetypes_cancel_auction_trade_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetypes',
            old_name='selection_purchaser_assert',
            new_name='selection_purchaser_assest',
        ),
    ]
