# Generated by Django 3.2.6 on 2021-10-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0045_rename_selection_purchaser_assert_messagetypes_selection_purchaser_assest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetypes',
            old_name='selection_purchaser_assest',
            new_name='selection_purchaser_assets',
        ),
    ]
