# Generated by Django 3.2.6 on 2021-10-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0047_auto_20211029_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankruptperson',
            old_name='insolvent_catrory_name',
            new_name='insolvent_category_name',
        ),
        migrations.AlterField(
            model_name='procedureprolongation',
            name='date',
            field=models.TextField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
