# Generated by Django 3.2.6 on 2021-10-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0048_auto_20211029_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher_person_v2',
            name='fio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.fio'),
        ),
    ]
