# Generated by Django 3.2.6 on 2021-10-29 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0049_alter_publisher_person_v2_fio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankruptfirm',
            name='insolvent_catrory_name',
        ),
        migrations.RemoveField(
            model_name='bankruptfirm',
            name='legal_addres',
        ),
        migrations.AddField(
            model_name='bankruptfirm',
            name='insolvent_caterory_name',
            field=models.TextField(blank=True, null=True, verbose_name='InsolventCategoryName'),
        ),
        migrations.AddField(
            model_name='bankruptfirm',
            name='legal_address',
            field=models.TextField(blank=True, null=True, verbose_name='LegalAddress'),
        ),
        migrations.AlterField(
            model_name='anotherpersonsforresponsibility',
            name='person_for_responsibility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.personforresponsibility'),
        ),
        migrations.AlterField(
            model_name='arbitrmanager',
            name='correspodence_address',
            field=models.TextField(blank=True, null=True, verbose_name='CorrespodenceAddress'),
        ),
        migrations.AlterField(
            model_name='arbitrmanager',
            name='first_name',
            field=models.TextField(blank=True, null=True, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='arbitrmanager',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='arbitrmanager',
            name='last_name',
            field=models.TextField(blank=True, null=True, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='arbitrmanager',
            name='middle_name',
            field=models.TextField(blank=True, verbose_name='MiddleName'),
        ),
        migrations.AlterField(
            model_name='arbitrmanager',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='arbitrmanager',
            name='reg_num',
            field=models.TextField(blank=True, null=True, verbose_name='RegNum'),
        ),
        migrations.AlterField(
            model_name='arbitrmanager',
            name='snils',
            field=models.TextField(blank=True, null=True, verbose_name='SNILS'),
        ),
        migrations.AlterField(
            model_name='bankrupt',
            name='bankrupt',
            field=models.TextField(blank=True, null=True, verbose_name='Bankrupt'),
        ),
        migrations.AlterField(
            model_name='bankrupt_company_v2',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='bankrupt_company_v2',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='bankrupt_company_v2',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bankrupt_company_v2',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='bankrupt_person_v2',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='bankrupt_person_v2',
            name='birth_place',
            field=models.TextField(blank=True, null=True, verbose_name='BirthPlace'),
        ),
        migrations.AlterField(
            model_name='bankrupt_person_v2',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='bankrupt_person_v2',
            name='snils',
            field=models.TextField(blank=True, null=True, verbose_name='SNILS'),
        ),
        migrations.AlterField(
            model_name='bankruptfirm',
            name='full_name',
            field=models.TextField(blank=True, null=True, verbose_name='FullName'),
        ),
        migrations.AlterField(
            model_name='bankruptfirm',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='bankruptfirm',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='bankruptfirm',
            name='okpo',
            field=models.TextField(blank=True, null=True, verbose_name='OKPO'),
        ),
        migrations.AlterField(
            model_name='bankruptfirm',
            name='post_address',
            field=models.TextField(blank=True, null=True, verbose_name='PostAddress'),
        ),
        migrations.AlterField(
            model_name='bankruptfirm',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='ShortName'),
        ),
        migrations.AlterField(
            model_name='bankruptinfo',
            name='bankrupt_category',
            field=models.TextField(blank=True, null=True, verbose_name='BankruptCategory'),
        ),
        migrations.AlterField(
            model_name='bankruptinfo',
            name='bankrupt_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.bankruptperson', verbose_name='BankruptPerson'),
        ),
        migrations.AlterField(
            model_name='bankruptinfo',
            name='bankrupt_type',
            field=models.TextField(blank=True, null=True, verbose_name='BankruptType'),
        ),
        migrations.AlterField(
            model_name='bankruptinfo',
            name='bankruptfirm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.bankruptfirm', verbose_name='BankruptFirm'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='BirthDate'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='birth_place',
            field=models.TextField(blank=True, null=True, verbose_name='BirthPlace'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='first_name',
            field=models.TextField(blank=True, null=True, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='insolvent_category_name',
            field=models.TextField(blank=True, null=True, verbose_name='InsolventCategoryName'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='last_name',
            field=models.TextField(blank=True, null=True, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='middle_name',
            field=models.TextField(blank=True, null=True, verbose_name='MiddleName'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='name_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.namehistoryitem', verbose_name='NameHistory'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='ogrnip',
            field=models.TextField(blank=True, null=True, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='snils',
            field=models.TextField(blank=True, null=True, verbose_name='SNILS'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='fio',
            name='first_name',
            field=models.TextField(blank=True, null=True, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='fio',
            name='last_name',
            field=models.TextField(blank=True, null=True, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='fio',
            name='middle_name',
            field=models.TextField(blank=True, null=True, verbose_name='MiddleName'),
        ),
        migrations.AlterField(
            model_name='fiohistory',
            name='fio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.fio'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizer',
            name='full_name',
            field=models.TextField(blank=True, null=True, verbose_name='FullName'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizer',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizer',
            name='legal_address',
            field=models.TextField(blank=True, null=True, verbose_name='LegalAddress'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizer',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizer',
            name='okpo',
            field=models.TextField(blank=True, null=True, verbose_name='OKPO'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizer',
            name='post_address',
            field=models.TextField(blank=True, null=True, verbose_name='PostAddress'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizer',
            name='short_name',
            field=models.TextField(blank=True, null=True, verbose_name='ShortName'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizeragent',
            name='first_name',
            field=models.TextField(blank=True, null=True, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizeragent',
            name='last_name',
            field=models.TextField(blank=True, null=True, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='firmtradeorganizeragent',
            name='middle_name',
            field=models.TextField(blank=True, null=True, verbose_name='MiddleName'),
        ),
        migrations.AlterField(
            model_name='fnsdepartment',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='fnsdepartment',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='foreignsystem',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='case_number',
            field=models.TextField(blank=True, null=True, verbose_name='Номер судебного дела'),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='message_guid',
            field=models.TextField(blank=True, null=True, verbose_name='MessageGUID'),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='number',
            field=models.TextField(blank=True, null=True, verbose_name='Номер сообщения'),
        ),
        migrations.AlterField(
            model_name='messageurl',
            name='download_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namehistoryitem',
            name='name_history_item',
            field=models.TextField(null=True, verbose_name='NameHistoryItem'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='first_name',
            field=models.TextField(blank=True, null=True, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='last_name',
            field=models.TextField(blank=True, null=True, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='middle_name',
            field=models.TextField(blank=True, null=True, verbose_name='MiddleName'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='organization_department_name',
            field=models.TextField(blank=True, null=True, verbose_name='OrganizationDepartmentName'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='organization_name',
            field=models.TextField(blank=True, null=True, verbose_name='OrganizationName'),
        ),
        migrations.AlterField(
            model_name='operatorsro',
            name='first_name',
            field=models.TextField(blank=True, null=True, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='operatorsro',
            name='last_name',
            field=models.TextField(blank=True, null=True, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='operatorsro',
            name='middle_name',
            field=models.TextField(blank=True, null=True, verbose_name='MiddleName'),
        ),
        migrations.AlterField(
            model_name='operatorsro',
            name='sro_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.sroinfo', verbose_name='SroInfo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.TextField(blank=True, null=True, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='person',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.TextField(blank=True, null=True, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.TextField(blank=True, null=True, verbose_name='MiddleName'),
        ),
        migrations.AlterField(
            model_name='persontradeorganizer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='persontradeorganizer',
            name='first_name',
            field=models.TextField(blank=True, null=True, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='persontradeorganizer',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='persontradeorganizer',
            name='last_name',
            field=models.TextField(blank=True, null=True, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='persontradeorganizer',
            name='middle_name',
            field=models.TextField(blank=True, null=True, verbose_name='MiddleName'),
        ),
        migrations.AlterField(
            model_name='persontradeorganizer',
            name='ogrnip',
            field=models.TextField(blank=True, null=True, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='xsi_type',
            field=models.TextField(blank=True, null=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_sro_v2',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_sro_v2',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_sro_v2',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_sro_v2',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_v2',
            name='correspondence_address',
            field=models.TextField(blank=True, null=True, verbose_name='Correspondence Address'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_v2',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_v2',
            name='ogrnip',
            field=models.TextField(blank=True, null=True, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='publisher_arbitr_manager_v2',
            name='snils',
            field=models.TextField(blank=True, null=True, verbose_name='SNILS'),
        ),
        migrations.AlterField(
            model_name='publisher_asv_v2',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_asv_v2',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_asv_v2',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='publisher_centralbankrf_v2',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_centralbankrf_v2',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_centralbankrf_v2',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='publisher_company_v2',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_company_v2',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_company_v2',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='publisher_efrsb_v2',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_firmtrade_organizer_v2',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_firmtrade_organizer_v2',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_firmtrade_organizer_v2',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='publisher_fnsdepartment_v2',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_fnsdepartment_v2',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_fnsdepartment_v2',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='publisher_mfc_v2',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_mfc_v2',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher_mfc_v2',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='publisher_person_v2',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_persontrade_organizer_v2',
            name='fio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.fio'),
        ),
        migrations.AlterField(
            model_name='publisher_persontrade_organizer_v2',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='publisher_persontrade_organizer_v2',
            name='ogrnip',
            field=models.TextField(blank=True, null=True, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='publisherinfo',
            name='arbitr_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.arbitrmanager', verbose_name='ArbitrManager'),
        ),
        migrations.AlterField(
            model_name='publisherinfo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='publisherinfo',
            name='firm_trade_organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.firmtradeorganizer', verbose_name='FirmTradeOrganizer'),
        ),
        migrations.AlterField(
            model_name='publisherinfo',
            name='fns_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.fnsdepartment', verbose_name='FnsDepartment'),
        ),
        migrations.AlterField(
            model_name='publisherinfo',
            name='foreign_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.foreignsystem', verbose_name='ForeingSystem'),
        ),
        migrations.AlterField(
            model_name='publisherinfo',
            name='operator_cbrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.operator', verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='publisherinfo',
            name='operator_sro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.operatorsro', verbose_name='OperatorSro'),
        ),
        migrations.AlterField(
            model_name='publisherinfo',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='publisherinfo',
            name='person_trade_organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.persontradeorganizer', verbose_name='PersonTradeOrganizer'),
        ),
        migrations.AlterField(
            model_name='publisherinfo',
            name='publisher_type',
            field=models.TextField(blank=True, null=True, verbose_name='PublisherType'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='LegalAddress'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='sro_name',
            field=models.TextField(blank=True, verbose_name='SroName'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='sro_registry_number',
            field=models.TextField(blank=True, verbose_name='SroRegistryNumber'),
        ),
        migrations.AlterField(
            model_name='sroinfo',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='sroinfo',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='LegalAddress'),
        ),
        migrations.AlterField(
            model_name='sroinfo',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sroinfo',
            name='ogrn',
            field=models.TextField(blank=True, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='sroinfo',
            name='post_address',
            field=models.TextField(blank=True, verbose_name='PostAddress'),
        ),
    ]
