# Generated by Django 3.2.6 on 2021-10-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0050_auto_20211029_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealinvalid',
            name='declaration_notice_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
