# Generated by Django 3.2.6 on 2021-10-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0052_rename_auctiot_lot_lottable_auction_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantperson',
            name='price_offer',
            field=models.FloatField(blank=True, null=True, verbose_name='PriceOffer'),
        ),
    ]
