# Generated by Django 3.2.6 on 2021-10-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0053_participantperson_price_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actdealinvalid',
            name='court_decision_notice_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actdealinvalid2',
            name='court_decision_notice_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actinfo',
            name='act_deal_invalid_message_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actreviewdealinvalid2',
            name='court_decision_notice_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annullmentmessage',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='application',
            name='time_begin',
            field=models.TextField(blank=True, null=True, verbose_name='TimeBegin'),
        ),
        migrations.AlterField(
            model_name='application',
            name='time_end',
            field=models.TextField(blank=True, null=True, verbose_name='TimeEnd'),
        ),
        migrations.AlterField(
            model_name='applicationsessionend',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='applicationsessionstart',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='applicationsessionstatistic',
            name='date_begin',
            field=models.TextField(blank=True, null=True, verbose_name='DateBegin'),
        ),
        migrations.AlterField(
            model_name='applicationsessionstatistic',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='appointadministration',
            name='administration_date_from',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointadministration',
            name='decision_date',
            field=models.TextField(blank=True, null=True, verbose_name='DecisionDate'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.TextField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='advance',
            field=models.TextField(blank=True, null=True, verbose_name='Advance'),
        ),
        migrations.AlterField(
            model_name='bankruptperson',
            name='birth_date',
            field=models.TextField(blank=True, null=True, verbose_name='BirthDate'),
        ),
        migrations.AlterField(
            model_name='beginexecutoryprocess',
            name='date_begin_executory_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biddingcancel',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='biddingend',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='biddingendbankruptcycreditor',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='biddingfail',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='biddinginvitation',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='biddingpause',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='biddingprocessinfo',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='biddingresult',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='biddingresume',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='biddingstart',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='changeadministration',
            name='decision_date',
            field=models.TextField(blank=True, null=True, verbose_name='DecisionDate'),
        ),
        migrations.AlterField(
            model_name='closeform',
            name='time_result',
            field=models.TextField(blank=True, null=True, verbose_name='TimeResult'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='meeting_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractinfo',
            name='date_contract',
            field=models.TextField(blank=True, null=True, verbose_name='DateContract'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='event_time',
            field=models.TextField(blank=True, null=True, verbose_name='EventTime'),
        ),
        migrations.AlterField(
            model_name='courtdecree',
            name='decision_date',
            field=models.TextField(blank=True, null=True, verbose_name='DecisionDate'),
        ),
        migrations.AlterField(
            model_name='creditorchoicerightsubsidiary',
            name='subsidiary_act_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealinfo',
            name='deal_invalid_message_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealinvalid',
            name='declaration_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disqualificationarbitrationmanager2',
            name='date_begin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='getdebtormessagescontentforperiodbyidbankrupt',
            name='startDate',
            field=models.TextField(blank=True, null=True, verbose_name='Дата начала периода'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='advance',
            field=models.TextField(blank=True, null=True, verbose_name='Advance'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='advance_percent',
            field=models.TextField(blank=True, null=True, verbose_name='AdvancePercent'),
        ),
        migrations.AlterField(
            model_name='meetingparticipantsbuilding',
            name='meeting_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingworker',
            name='ballots_reception_end_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingworkerresult',
            name='meeting_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingworkerresult',
            name='meeting_notice_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='publish_date',
            field=models.TextField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='objectofassessment',
            name='date_of_assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openform',
            name='time_begin',
            field=models.TextField(blank=True, null=True, verbose_name='TimeBegin'),
        ),
        migrations.AlterField(
            model_name='openform',
            name='time_end',
            field=models.TextField(blank=True, null=True, verbose_name='TimeEnd'),
        ),
        migrations.AlterField(
            model_name='receivingcreditordemand',
            name='demand_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivingcreditordemand',
            name='demand_sum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reducingsizesharecapital',
            name='normative_act_add_option_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnofapplicationonextrajudicialbankruptcy',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salecontractinfo',
            name='conclusion_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salecontractresult',
            name='date_contract',
            field=models.TextField(blank=True, null=True, verbose_name='DateContract'),
        ),
        migrations.AlterField(
            model_name='saleorderpledgedproperty',
            name='meeting_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startsettlement',
            name='settlement_start_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terminationadministraion',
            name='decision_date',
            field=models.TextField(blank=True, null=True, verbose_name='DecisionDate'),
        ),
        migrations.AlterField(
            model_name='tradeinfo',
            name='date_publish_efir',
            field=models.TextField(blank=True, null=True, verbose_name='DatePublishEFIR'),
        ),
        migrations.AlterField(
            model_name='transferassertsforimplementation',
            name='date_sumbmit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferinsuranceportfolio',
            name='expected_delivery_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferownershiprealestate',
            name='court_decision_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferownershiprealestate',
            name='transfer_ownership_state_registration_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viewdraftrestructuringplan',
            name='date_end_restructuring_plan_execution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viewexecrestructuringplan',
            name='date_end_restructuring_plan_execution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
