# Generated by Django 3.2.6 on 2021-10-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0054_auto_20211031_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annullmentmessage',
            name='id_annulment',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID_Annulment'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_identifier',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biddingstatelotinfo',
            name='lot_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='LotNumber'),
        ),
        migrations.AlterField(
            model_name='creditorlotnumber',
            name='lot_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='LotNumber'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='day',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duration',
            name='month',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duration',
            name='year',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='getmessagecontent',
            name='get_message_content_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор сообщения в ЕФРСБ'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='LotNumber'),
        ),
        migrations.AlterField(
            model_name='lotcontractsale',
            name='lot_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='LotNumber'),
        ),
        migrations.AlterField(
            model_name='lotinfo',
            name='lot_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='LotNumber'),
        ),
        migrations.AlterField(
            model_name='lotstatistic',
            name='accept_count',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='AcceptCount'),
        ),
        migrations.AlterField(
            model_name='lotstatistic',
            name='entry_count',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='EntryCount'),
        ),
        migrations.AlterField(
            model_name='lotstatistic',
            name='lot_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='LotNumber'),
        ),
        migrations.AlterField(
            model_name='lottraderesult',
            name='lot_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='LotNumber'),
        ),
        migrations.AlterField(
            model_name='meetingworkerresult',
            name='workers_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='bankruptid',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='BankruptId'),
        ),
        migrations.AlterField(
            model_name='participantperson',
            name='ogrnip',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='OGRNIP'),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='lot_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='LotNumber'),
        ),
        migrations.AlterField(
            model_name='salecontractinfo',
            name='lot_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='id_efrsb',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID_EFRSB'),
        ),
    ]
