# Generated by Django 3.2.6 on 2021-11-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0055_auto_20211031_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankruptsupervisoryperson',
            name='responsibility_amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personforresponsibility',
            name='responsibility_amount',
            field=models.TextField(blank=True, null=True),
        ),
    ]
