# Generated by Django 3.2.6 on 2021-11-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0056_auto_20211101_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeauction',
            name='additional_text',
            field=models.TextField(blank=True, null=True, verbose_name='AdditionalText'),
        ),
        migrations.AddField(
            model_name='changeauction',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.application', verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='changeauction',
            name='date',
            field=models.TextField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='changeauction',
            name='id_trade_place',
            field=models.TextField(blank=True, null=True, verbose_name='IdTradePlace'),
        ),
        migrations.AddField(
            model_name='changeauction',
            name='is_repeat',
            field=models.BooleanField(blank=True, null=True, verbose_name='IsRepeat'),
        ),
        migrations.AddField(
            model_name='changeauction',
            name='lot_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xmlinport.lottable', verbose_name='LotTable'),
        ),
        migrations.AddField(
            model_name='changeauction',
            name='price_type',
            field=models.TextField(blank=True, null=True, verbose_name='PriceType'),
        ),
        migrations.AddField(
            model_name='changeauction',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='changeauction',
            name='trade_site',
            field=models.TextField(blank=True, null=True, verbose_name='TradeSite'),
        ),
        migrations.AddField(
            model_name='changeauction',
            name='trade_type',
            field=models.TextField(blank=True, null=True, verbose_name='TradeType'),
        ),
    ]
