# Generated by Django 3.2.6 on 2021-12-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlinport', '0057_auto_20211101_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='step_price',
            field=models.FloatField(blank=True, null=True, verbose_name='StepPrice'),
        ),
    ]
